# Generated by Django 3.1.5 on 2021-02-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='ShoppingCart',
        ),
    ]
