# Generated by Django 3.1.5 on 2021-01-31 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='niunius/blog_img')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.article')),
            ],
        ),
    ]
