# Generated by Django 3.1.5 on 2021-02-16 18:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niunius', '0002_auto_20210216_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(max_length=64)),
                ('address_zipcode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='\\d{2}-\\d{3}')])),
                ('address_street', models.CharField(max_length=64)),
                ('address_country', models.CharField(max_length=64)),
                ('paid', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.shoppingcart')),
            ],
        ),
    ]
