# Generated by Django 3.1.5 on 2021-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
    ]
