# Generated by Django 3.1.5 on 2021-02-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0004_auto_20210201_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentProduct',
        ),
    ]
