# Generated by Django 3.1.5 on 2021-02-18 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niunius', '0004_auto_20210218_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Artykuł-komentarz', 'verbose_name_plural': 'Artykuł-komentarze'},
        ),
        migrations.AlterModelOptions(
            name='articlephoto',
            options={'verbose_name': 'Artykuł-zdjęcie', 'verbose_name_plural': 'Artykuł-zdjęcia'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Auta', 'verbose_name_plural': 'Auto'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'W koszyku', 'verbose_name_plural': 'W koszyku'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Koszyk', 'verbose_name_plural': 'Koszyki'},
        ),
        migrations.AlterField(
            model_name='article',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dodano'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Nie lubię'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Lubię'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Użytkownik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dodano'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.article', verbose_name='Artykuł'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='articlephoto',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.article', verbose_name='Artykuł'),
        ),
        migrations.AlterField(
            model_name='articlephoto',
            name='photo',
            field=models.ImageField(upload_to='niunius/blog_img', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='niunius/car_img/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64, unique=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.shoppingcart', verbose_name='Koszyk'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_city',
            field=models.CharField(max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_country',
            field=models.CharField(max_length=64, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_street',
            field=models.CharField(max_length=64, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_zipcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='\\d{2}-\\d{3}')], verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='niunius.shoppingcart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Zapłacone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dodano'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(to='niunius.Car', verbose_name='Pasuje do auta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='niunius.Category', verbose_name='Należy do kategorii'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=128, verbose_name='Kod produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='niunius/product_img/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Dostępność'),
        ),
    ]
