# Generated by Django 3.1.5 on 2021-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0005_auto_20210218_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
