# Generated by Django 3.1.5 on 2021-02-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0006_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
