# Generated by Django 3.1.5 on 2021-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0007_product_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
