# Generated by Django 3.1.5 on 2021-02-20 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0007_delete_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ilość'),
        ),
    ]
