# Generated by Django 3.1.5 on 2021-02-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0008_auto_20210220_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data zamówienia'),
        ),
    ]
