# Generated by Django 3.1.5 on 2021-02-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0011_carservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarService',
        ),
    ]
