# Generated by Django 3.1.5 on 2021-02-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niunius', '0012_delete_carservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(choices=[('JANUARY', 'Styczeń'), ('FEBRUARY', 'Luty'), ('MARCH', 'Marzec'), ('APRIL', 'Kwiecień'), ('MAY', 'Maj'), ('JUNE', 'Czerwiec'), ('JULY', 'Lipiec'), ('AUGUST', 'Sierpień'), ('SEPTEMBER', 'Wrzesień'), ('OCTOBER', 'Październik'), ('NOVEMBER', 'Listopad'), ('DECEMBER', 'Grudzień')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niunius.servicestation')),
            ],
        ),
    ]
