# Generated by Django 3.1.5 on 2021-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0014_auto_20210223_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa usługi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Cena')),
                ('time', models.IntegerField(null=True, verbose_name='Czas trwania')),
            ],
            options={
                'verbose_name': 'Warsztat - usługa',
                'verbose_name_plural': 'Warsztat - usługi',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
