# Generated by Django 3.1.5 on 2021-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0016_auto_20210226_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Kurier', 'Kurier'), ('Odbiór własny', 'Odbiór własny')], default='Kurier', max_length=32, verbose_name='Sposób dostawy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Przelwe', 'Przelew'), ('Płatność przy odbiorze', 'Płatność przy odbiorze')], default='Przelew', max_length=32, verbose_name='Sposób płatności'),
            preserve_default=False,
        ),
    ]
