# Generated by Django 3.1.5 on 2021-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0017_auto_20210227_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Przelew', 'Przelew'), ('Płatność przy odbiorze', 'Płatność przy odbiorze')], max_length=32, verbose_name='Sposób płatności'),
        ),
    ]
