# Generated by Django 3.1.5 on 2021-02-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0020_auto_20210227_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_buyer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_buyer_first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_buyer_last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
