# Generated by Django 3.1.5 on 2021-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0024_auto_20210228_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='is_ordered',
            field=models.BooleanField(null=True),
        ),
    ]
