# Generated by Django 3.1.5 on 2021-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0025_auto_20210228_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Zmieniono'),
        ),
    ]
