# Generated by Django 3.1.5 on 2021-02-28 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niunius', '0027_auto_20210228_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dostępność'),
        ),
    ]
